### ISSUE TITLE
Apresentação dos dados levantados

### ISSUE THREAD

**Issue by marcelosalles** [marcelosalles/otimizacao-logistica-e-transportes#2]
Como estou pensando em elaborar o trabalho por aqui, vou precisar expor os dados de alguma forma. Acho que vou tentar usar o pandas pra fazer um data.frame com os dados que eu levantei

**Comment by xmnlab** [comment]
Que ótimo!

**Comment by marcelosalles** [comment]
o pandas deu certo!
